# Generated by Django 5.2.8 on 2025-12-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRecord',
        ),
    ]
